name: one1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.2.0
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  animated_check: ^1.0.0
  firebase_core: any
  firebase_auth: ^4.17.4
  firebase_database: any
  intl: ^0.18.1
  fl_chart: ^0.63.0
  flutter_local_notifications: ^19.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/1.jpeg

